/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package logic;


import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Vector;

import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.table.TableColumn;

import com.microsoft.z3.ApplyResult;
import com.microsoft.z3.ArithExpr;
import com.microsoft.z3.BoolExpr;
import com.microsoft.z3.Context;
import com.microsoft.z3.Expr;
import com.microsoft.z3.Goal;
import com.microsoft.z3.Solver;
import com.microsoft.z3.Status;
import com.microsoft.z3.Tactic;

/**
 *
 * @author ad31
 */
public class Fenetre extends javax.swing.JFrame {

    /**
     * Creates new form Fenetre
     */
    public Fenetre() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jFileChooser3 = new javax.swing.JFileChooser();
        jDialog2 = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jButton6 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();

        jFileChooser3.setMinimumSize(new java.awt.Dimension(200, 301));
        jFileChooser3.setName(""); // NOI18N
        jFileChooser3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFileChooser3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addComponent(jFileChooser3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addComponent(jFileChooser3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        jLabel3.setText("Enregistré :");

        jLabel4.setText("T");

        jButton9.setText("Fermer");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog2Layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                .addGap(121, 121, 121))
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jButton9))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jButton1.setText("Ouvrir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Un modèle");
        jButton3.setEnabled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jTextPane1);

        jButton6.setText("Enr. simple");
        jButton6.setEnabled(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jButton3)
                .addGap(162, 162, 162)
                .addComponent(jButton6)
                .addContainerGap(154, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton6))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Modèle(s)", jPanel1);

        jScrollPane2.setViewportView(jTextPane2);

        jButton5.setText("Calculer");
        jButton5.setEnabled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton7.setText("Enr. complex");
        jButton7.setEnabled(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton5)
                .addGap(18, 18, 18)
                .addComponent(jButton7)
                .addContainerGap(313, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton7))
                .addGap(0, 7, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Impliqués premiers", jPanel2);

        jTable2.setModel(new Tablemodel());
        JComboBox combochoix = new JComboBox(Choix.values());
        jTable2.setCellEditor(new DefaultCellEditor(combochoix));
        jTable2.setColumnSelectionAllowed(true);
        jScrollPane3.setViewportView(jTable2);
        TableColumn tc = jTable2.getColumn("Valeur");
        tc.setCellRenderer(new Tablecomp());
        tc.setCellEditor(new DefaultCellEditor(combochoix));
        jTable2.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 516, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Prédét. Argument(s)", jPanel3);

        jButton2.setText("Test de satisfiabilité");
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Chemin");

        jButton8.setText("Effacer");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jDialog1.setBounds(0, 0, 550,350);
        if (path != null) jFileChooser3.setSelectedFile(path);
        jDialog1.setVisible(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jFileChooser3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileChooser3ActionPerformed
        // TODO add your handling code here:        
        if (evt.getActionCommand().equals("CancelSelection")){
            jDialog1.setVisible(false);
            return;
        }
        f = jFileChooser3.getSelectedFile().getPath();
        fichier  = jFileChooser3.getSelectedFile().getName();
        path =jFileChooser3.getSelectedFile();
        System.out.println(f);

        jLabel2.setText(f);
        i=0;
         ctx = new Context();
        // vecteur des sommets
         Sommet.carac_sommets =new HashMap<String, Sommet>();
         Sommet.table= new Vector<>(); 
        // vecteur des arcs d'appui
         arc.carac_appuis = new HashMap<String, arc>();
        // vecteur des arcs d'attaque
         arc.carac_attaques = new HashMap<String, arc>();
         
        try{

            InputStream ips=new FileInputStream(f); 
            InputStreamReader ipsr=new InputStreamReader(ips);
            BufferedReader br=new BufferedReader(ipsr);
            String ligne;
            String g;
            while ((ligne=br.readLine())!=null){
                System.out.println(ligne);
                if (ligne.equals("ARG:")){
                    while ((ligne=br.readLine())!=null&&(!(ligne.equals(".")))){
                        g=ligne.substring(1, ligne.length()-1);
                        String[] t =g.split(",");
                        Sommet.carac_sommets.put(t[0],new Sommet(t[0],ctx));
                    }
                }
                if (ligne.equals("ATT:")){
                    while ((ligne=br.readLine())!=null&&(!(ligne.equals(".")))){
                        g=ligne.substring(1, ligne.length()-1);
                        String[] t =g.split(",");
                        arc.carac_attaques.put(t[0],new arc(t[0],t[1], t[2], ctx, true));
                    }

                }

                if (ligne.equals("APP:")){
                    while ((ligne=br.readLine())!=null&&(!(ligne.equals(".")))){
                        g=ligne.substring(1, ligne.length()-1);
                        String[] t =g.split(",");
                        arc.carac_appuis.put(t[0],new arc(t[0],t[1], t[2], ctx, false));
                    }
                }
            }
            br.close(); 
           }		
           catch (Exception e){
                System.out.println(e.toString());
           }
        
         jDialog1.setVisible(false);
         jButton2.setEnabled(true);
         jButton3.setEnabled(true);
         jButton5.setEnabled(true);
         jButton6.setEnabled(true);
         jButton7.setEnabled(true);
         reset();
         
         jTable2.updateUI();
    }//GEN-LAST:event_jFileChooser3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jButton2.setEnabled(false);
        jLabel1.setText("");
        Solver s = resolution();
        Status st;
        jLabel1.setText((st=s.check()).toString());
        if (st.equals(Status.SATISFIABLE)){
        jTextPane1.setText(s.getModel().toString());
        }else{
            jTextPane1.setText("");
        }
        jButton2.setEnabled(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Solver s = resolution();
        jLabel1.setText("");
        Status st;
        jLabel1.setText((st=s.check()).toString());
        if (st.equals(Status.SATISFIABLE)){
            String truc=s.getModel().toString();
            jTextPane1.setText(s.getModel().toString());
        }else{
            jTextPane1.setText("");
        }        
    }//GEN-LAST:event_jButton3ActionPerformed
 
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Solver s = resolutionbis();
        Status st = s.check();
        jLabel1.setText(st.toString());
        Goal g = ctx.mkGoal(true, false, false);
        for (BoolExpr b : s.getAssertions()){
            g.add(b);
        }
        ApplyResult ar = applyTactic(ctx, ctx.repeat(ctx.andThen(ctx.mkTactic("simplify"),
                ctx.mkTactic("solve-eqs")), 10), g);

        
        Solver s1 = ctx.mkSolver();

                
        for (BoolExpr e : ar.getSubgoals()[0].getFormulas())
        {            
            s1.add(e);
        }

        System.out.println(ar.toString());

                jTextPane2.setText(s1.toString());

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
                    String file;
            file = f;
            file = file.replace(fichier, "simple");
            File theDir = new File(file);
            boolean result =true;
// if the directory does not exist, create it
            if (!theDir.exists()) {
             result = false;
            try{
                theDir.mkdir();
                result = true;
            } 
            catch(SecurityException se){
                //handle it
            }        

        }

            file =file.concat("/"+fichier+"bis");
            try{
                
                FileOutputStream ips = new FileOutputStream(file);
                OutputStreamWriter ipsr = new OutputStreamWriter(ips);
            BufferedWriter br=new BufferedWriter(ipsr);
            String ligne;
            String g;
            br.write("; Sommet(s) :\n");
            for (Sommet s : Sommet.carac_sommets.values()){
                br.write("; "+s.id+" PréDef : "+s.chx.toString()+"\n");
            }
            br.write("; Arc(s) appui(s):\n");
           for (arc a : arc.carac_appuis.values()){
                br.write("; ("+a.id+", "+a.ori+", "+a.dest+")\n");
            }
            br.write("; Arc(s) attaque(s):\n");
           for (arc a : arc.carac_attaques.values()){
                br.write("; ("+a.id+", "+a.ori+", "+a.dest+")\n");
            }
           
           Solver s =resolution();
           br.write("\n\n;Traduction triviale \n");
           br.write(s.toString());
           
           br.write("(check-sat) \n");
           
           br.write(";Résultat : \n");
           br.write(";"+s.check());
            jTextPane1.setText(s.toString());
            br.close(); 
           }		
           catch (Exception e){
                System.out.println(e.toString());
           }
            if (result) {register(file);}
            
    }//GEN-LAST:event_jButton6ActionPerformed

    private void register(String texte){
        jDialog2.setSize(texte.length()*8, 150);
        jLabel4.setText(texte);
        jDialog2.setVisible(true);
    }
    
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
            jButton6ActionPerformed(evt);
            String file;
            file = f;
            file = file.replace(fichier, "complexe");
            File theDir = new File(file);
            boolean result =true;
// if the directory does not exist, create it
            if (!theDir.exists()) {
            result = false;
            try{
                theDir.mkdir();
                result = true;
            } 
            catch(SecurityException se){
                //handle it
            }        

        }

            file =file.concat("/"+fichier+"bis");
            try{
                
                FileOutputStream ips = new FileOutputStream(file);
                OutputStreamWriter ipsr = new OutputStreamWriter(ips);
            BufferedWriter br=new BufferedWriter(ipsr);
            String ligne;
            String g;
            br.write("; Sommet(s) :\n");
            for (Sommet s : Sommet.carac_sommets.values()){
                br.write("; "+s.id+" PréDef : "+s.chx.toString()+"\n");
            }
            br.write("; Arc(s) appui(s):\n");
           for (arc a : arc.carac_appuis.values()){
                br.write("; ("+a.id+", "+a.ori+", "+a.dest+")\n");
            }
            br.write("; Arc(s) attaque(s):\n");
           for (arc a : arc.carac_attaques.values()){
                br.write("; ("+a.id+", "+a.ori+", "+a.dest+")\n");
            }
           
           Solver s =resolutionbis();
           br.write("\n\n;Traduction triviale \n");
           br.write(s.toString());
           
           br.write("(check-sat) \n");
           
           br.write(";Résultat : \n");
           br.write(";"+s.check());
           jLabel1.setText(s.check().toString());
            Goal go = ctx.mkGoal(true, false, false);
        for (BoolExpr b : s.getAssertions()){
            go.add(b);
        }
        ApplyResult ar;
        ar = applyTactic(ctx, ctx.repeat(ctx.andThen(ctx.mkTactic("simplify"),
                ctx.mkTactic("solve-eqs")), 10), go);
        Solver s1 = ctx.mkSolver();

                
        for (BoolExpr e : ar.getSubgoals()[0].getFormulas())
        {            
            s1.add(e);
        }
        br.write("\n\n(apply (repeat (then simplify solve-eqs) 10)) \n");
        jTextPane2.setText(s1.toString());
           br.write("\n\n;Traduction simplifié \n");
           br.write(s1.toString());
            
        br.close(); 
           }		
           catch (Exception e){
                System.out.println(e.toString());
           }

                        if (result) {register(file);}

    }//GEN-LAST:event_jButton7ActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        jDialog2.setVisible(false);
    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fenetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fenetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fenetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fenetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fenetre().setVisible(true);
            }
        });
    }
    // Fonction dans un exemple pour java 
        ApplyResult applyTactic(Context ctx, Tactic t, Goal g)
    {
        System.out.println("\nGoal: " + g);

        ApplyResult res = t.apply(g);
        System.out.println("Application result: " + res);

        Status q = Status.UNKNOWN;
        for (Goal sg : res.getSubgoals())
            if (sg.isDecidedSat())
                q = Status.SATISFIABLE;
            else if (sg.isDecidedUnsat())
                q = Status.UNSATISFIABLE;

        switch (q)
        {
        case UNKNOWN:
            System.out.println("Tactic result: Undecided");
            break;
        case SATISFIABLE:
            System.out.println("Tactic result: SAT");
            break;
        case UNSATISFIABLE:
            System.out.println("Tactic result: UNSAT");
            break;
        }

        return res;
    }
    
        void modelConverterTest(Context ctx)
    {
        System.out.println("ModelConverterTest");

        ArithExpr xr = (ArithExpr) ctx.mkConst(ctx.mkSymbol("x"),
                ctx.mkRealSort());
        ArithExpr yr = (ArithExpr) ctx.mkConst(ctx.mkSymbol("y"),
                ctx.mkRealSort());
        Goal g4 = ctx.mkGoal(true, false, false);
        g4.add(ctx.mkGt(xr, ctx.mkReal(10, 1)));
        g4.add(ctx.mkEq(yr, ctx.mkAdd(xr, ctx.mkReal(1, 1))));
        g4.add(ctx.mkGt(yr, ctx.mkReal(1, 1)));

        ApplyResult ar = applyTactic(ctx, ctx.mkTactic("simplify"), g4);


        ar = applyTactic(ctx, ctx.andThen(ctx.mkTactic("simplify"),
                ctx.mkTactic("solve-eqs")), g4);


        Solver s = ctx.mkSolver();
        for (BoolExpr e : ar.getSubgoals()[0].getFormulas())
            s.add(e);
        Status q = s.check();
        System.out.println("Solver says: " + q);
        System.out.println("Model: \n" + s.getModel());
        System.out.println("Converted Model: \n"
                + ar.convertModel(0, s.getModel()));

    }
    
    
        private Solver resolution(){
        
        Solver s=ctx.mkSolver();
	     
	     
	for (arc temp :arc.carac_attaques.values()){
		BoolExpr bool;
		BoolExpr bool2;
		if (!temp.dest.contains("to")){
		int i=0;
		
		BoolExpr ina=ctx.mkBoolConst("In"+temp.dest);
		bool2=ctx.mkImplies(ina,ctx.mkNot(Sommet.carac_sommets.get(temp.dest).bool));
		for (BoolExpr test : s.getAssertions()){
			if (test.equals(bool2)){
				i=1;
			}
		}
		bool=ctx.mkImplies(ctx.mkAnd(arc.active(temp, ctx, true, true), Sommet.carac_sommets.get(temp.ori).bool), 
		ina);
		s.add(bool);
		if(i==0) s.add(bool2);
		}
	}
	
	
	for (arc temp : arc.carac_appuis.values()){
		BoolExpr bool;
		if (!(temp.ori.contains("to")||temp.dest.contains("to"))){
		//Idem que l'attaque pour Pra
		BoolExpr pra=ctx.mkBoolConst("Pr"+temp.ori);
		BoolExpr bool2 = ctx.mkImplies(pra,Sommet.carac_sommets.get(temp.ori).bool);
		for (BoolExpr test : s.getAssertions()){
			if (test.equals(bool2)){
				i=1;
			}
		}
		bool=ctx.mkImplies(ctx.mkAnd(arc.active(temp, ctx, true, false),Sommet.carac_sommets.get(temp.dest).bool),
		pra);
		s.add(bool);
		if(i==0) s.add(bool2);
		}
	}
        
        for(Sommet temp: Sommet.table){
            if (temp.chx==Choix.TRUE){
                s.add(temp.bool);
            }
            else {
                if (temp.chx==Choix.FALSE){
                    s.add(ctx.mkNot(temp.bool));
                }
            }
        }

        return s;
    };
    
        
        private Solver resolutionbis(){
        
        Solver s=ctx.mkSolver();
	     
	     
	for (arc temp :arc.carac_attaques.values()){
		BoolExpr bool;
		BoolExpr bool2;
		if (!temp.dest.contains("to")){
		int i=0;
		
		//BoolExpr ina=ctx.mkBoolConst("In"+temp.dest);
		bool2=ctx.mkNot(Sommet.carac_sommets.get(temp.dest).bool);

		bool=ctx.mkImplies(ctx.mkAnd(arc.active(temp, ctx, true, true), Sommet.carac_sommets.get(temp.ori).bool), 
		bool2);
		s.add(bool);
                }

	}
	
	
	for (arc temp : arc.carac_appuis.values()){
		BoolExpr bool;
		if (!(temp.ori.contains("to")||temp.dest.contains("to"))){
		//Idem que l'attaque pour Pra
		BoolExpr bool2 = Sommet.carac_sommets.get(temp.ori).bool;
		bool=ctx.mkImplies(ctx.mkAnd(arc.active(temp, ctx, true, false),Sommet.carac_sommets.get(temp.dest).bool),
		bool2);
		s.add(bool);
                }
	}
        
        for(Sommet temp: Sommet.table){
            if (temp.chx==Choix.TRUE){
                s.add(temp.bool);
            }
            else {
                if (temp.chx==Choix.FALSE){
                    s.add(ctx.mkNot(temp.bool));
                }
            }
        }
        


        return s;
    };
            
        void reset(){
            jTextPane1.setText("");
            jTextPane2.setText("");
        }
    private File path;
    private Context ctx;
    private String f;
    private String fichier;
    private int i;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JFileChooser jFileChooser3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    // End of variables declaration//GEN-END:variables
}
